# Generated by Django 4.2.20 on 2025-04-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="category", max_length=100, unique=True),
        ),
    ]
