# Generated by Django 4.2.20 on 2025-04-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_category_slug"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exchangeproposal",
            unique_together={("ad_sender", "ad_receiver")},
        ),
    ]
