# Generated by Django 4.2.20 on 2025-04-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_exchangeproposal_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exchangeproposal",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="exchangeproposal",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="exchangeproposal",
            unique_together={("ad_sender", "ad_receiver", "is_active")},
        ),
    ]
